export const DEPARTMENT_NAMES = {
  "AAAD": "African, African-American, Diaspora Studies",
  "AERO": "Aerospace Studies",
  "AHSC": "Allied Health Sciences",
  "AMST": "American Studies",
  "ANTH": "Anthropology",
  "APPL": "Applied Sciences",
  "ARAB": "Arabic",
  "ARCH": "Archaeology",
  "ARMY": "Army",
  "ARTH": "Art History",
  "ARTS": "Studio Art",
  "ASIA": "Asian Studies",
  "ASTR": "Astronomy",
  "BBSP": "Biological And Biomedical Sciences",
  "BCB": "Bioinformatics And Computational Biology",
  "BIOC": "Biochemistry",
  "BIOL": "Biology",
  "BIOS": "Biostatistics",
  "BMME": "Biomedical Engineering",
  "BUSA": "Business-Study Abroad",
  "BUSG": "Global Scholars Program",
  "BUSI": "Business Administration",
  "CBIO": "Cell And Development Biology",
  "CBMC": "Chemical Biology And Medicinal Chemistry",
  "CHEM": "Chemistry",
  "CHER": "Cherokee",
  "CHIN": "Chinese",
  "CLAR": "Classical Archaeology",
  "CLAS": "Classics",
  "CLSC": "Clinical Laboratory Science",
  "CMPL": "Comparative Literature",
  "COMM": "Communication Studies",
  "COMP": "Computer Science",
  "CRMH": "Clinical Rehabilitation And Mental Health Counsel",
  "CZCH": "Czech",
  "DENG": "Dental Graduate Course",
  "DHED": "Dental Hygiene Education",
  "DHYG": "Dental Hygiene",
  "DPET": "Experimental Therapeutics",
  "DPOP": "Pharmacy Outcomes And Policy",
  "DRAM": "Dramatic Art",
  "DTCH": "Dutch",
  "ECON": "Economics",
  "EDMX": "Experienced Teacher Education",
  "EDUC": "Education",
  "ENDO": "Endodontics",
  "ENEC": "Environment And Ecology",
  "ENGL": "English",
  "ENVR": "Environment Sciences",
  "EPID": "Epidemiology",
  "EURO": "Contemporary European Studies",
  "EXSS": "Exercise And Sport Science",
  "FOLK": "Folklore",
  "FREN": "French",
  "GEOG": "Geography",
  "GEOL": "Geology",
  "GERJ": "Joint German At Duke",
  "GERM": "German",
  "GLBL": "Global Studies",
  "GNET": "Genetics And Molecular Biology",
  "GRAD": "Graduate Studies",
  "GREK": "Greek",
  "GSLL": "Germanic And Slavic Languages And Literatures",
  "HBEH": "Health Behavior",
  "HEBR": "Hebrew",
  "HIST": "History",
  "HMSC": "Human Movement Science",
  "HNRS": "Honors",
  "HNUR": "Hindi/Urdu",
  "HPM": "Health Policy And Management",
  "ICMU": "Introduction To Clinical Medicine Undergraduate",
  "IDST": "Interdisciplinary Studies",
  "IHMS": "Interdisciplinary Human Movement Science",
  "INLS": "Information & Library Science",
  "ISP": "International Student Program",
  "ITAL": "Italian",
  "JAPN": "Japanese",
  "JOMC": "Journalism And Mass Communication",
  "JWST": "Jewish Studies",
  "KOR": "Korean",
  "LATN": "Latin",
  "LAW": "Law",
  "LFIT": "Lifetime Fitness",
  "LFXP": "Law Exchange Program",
  "LGLA": "Lingala Language",
  "LING": "Linguistics",
  "LTAM": "Latin American Studies",
  "MAC": "Masters Of Accounting",
  "MASC": "Marine Science",
  "MATH": "Mathematics",
  "MBA": "Masters Of Business Administration",
  "MCRO": "Microbiology",
  "MEDF": "Medicine Fees",
  "MEDI": "Medicine",
  "MEJO": "Media And Journalism",
  "MHCH": "Maternal And Child Health",
  "MNGT": "Management And Society",
  "MOPH": "Molecular Pharmaceutics",
  "MTEC": "Medical Translational Education At Carolina",
  "MTSC": "Material Science",
  "MUSC": "Music",
  "NAVS": "Naval Science",
  "NBIO": "Neurobiology",
  "NURS": "Nursing",
  "NUSJ": "National Univerisity Of Singapore Joint Programs",
  "NUTR": "Health Nutrition",
  "OBIO": "Oral Biology",
  "OCCT": "Medical Allied Health Professions",
  "OCSC": "Occupational Science",
  "OPER": "Dentistry Operative",
  "ORAD": "Oral Radiology",
  "ORPA": "Oral Pathology",
  "ORTH": "Orthodontics",
  "PACE": "Practice Advancement And Clinical Education",
  "PATH": "Pathology",
  "PEDO": "Pediatric Dentistry",
  "PERI": "Periodontology",
  "PHCO": "Pharmacology",
  "PHCY": "Pharmacy  (Non-Departmental)",
  "PHIL": "Philosophy",
  "PHNU": "Public Health Nursing",
  "PHRS": "Pharmaceutical Sciences",
  "PHYA": "Physical Activities",
  "PHYI": "Physiology",
  "PHYS": "Physics",
  "PHYT": "Physical Therapy",
  "PLAN": "City And Regional Planning",
  "PLCY": "Public Policy",
  "PLSH": "Polish",
  "POLI": "Political Science",
  "PORT": "Portuguese",
  "PROS": "Prosthodontics",
  "PRSN": "Persian",
  "PSYC": "Psychology",
  "PUBA": "Public Administration",
  "PUBH": "Public Health",
  "PWAD": "Peace War & Defense",
  "RADG": "Radiography",
  "RADI": "Radiologic Science",
  "RECR": "Recreation And Leisure Studies",
  "RELI": "Religious Studies",
  "ROML": "Romance Languages",
  "RUSS": "Russian",
  "SECR": "Serbian And Croatian",
  "SLAV": "Slavic Languages",
  "SOCI": "Sociology",
  "SOWO": "Social Work",
  "SPAN": "Spanish",
  "SPCL": "Experiential And Special Studies",
  "SPHG": "School Of Public Health General",
  "SPHS": "Speech & Hearing Sciences",
  "STOR": "Statistics And Operations Research",
  "SWAH": "Swahili",
  "TOXC": "Toxicology",
  "TURK": "Turkish",
  "WMST": "Women Studies",
  "WOLO": "Wolof Language",
  "YAP": "Year Abroad Program",
  "CHWA": "Chichewa",
  "HUNG": "Hungarian",
  "MACD": "Macedonian",
  "MAYA": "Yucatec Maya",
  "CATA": "Catalan"
}

export enum Departments {
  AERO,
  AAAD,
  CHWA,
  LGLA,
  SWAH,
  WOLO,
  AMST,
  CHER,
  FOLK,
  HIST,
  ANTH,
  APPL,
  MTSC,
  ARCH,
  ARTH,
  ARTS,
  ASIA,
  ARAB,
  CHIN,
  HEBR,
  JAPN,
  HNUR,
  PRSN,
  TURK,
  BIOC,
  BIOL,
  COMP,
  BMME,
  ENVR,
  BIOS,
  CBIO,
  PHYI,
  CHEM,
  PLAN,
  CLAR,
  CLAS,
  GREK,
  LATN,
  COMM,
  MATH,
  DRAM,
  ECON,
  CMPL,
  ENGL,
  FREN,
  ENEC,
  EURO,
  EXSS,
  RECR,
  LFIT,
  PHYA,
  GEOG,
  GEOL,
  GSLL,
  DTCH,
  GERM,
  CZCH,
  HUNG,
  MACD,
  PLSH,
  RUSS,
  SECR,
  SLAV,
  GLBL,
  IDST,
  LTAM,
  SPAN,
  LING,
  MAYA,
  MASC,
  MCRO,
  ARMY,
  MUSC,
  NAVS,
  NUTR,
  PATH,
  PWAD,
  PHIL,
  ASTR,
  PHYS,
  POLI,
  PSYC,
  STOR,
  PLCY,
  RELI,
  JWST,
  CATA,
  ITAL,
  PORT,
  ROML,
  MNGT,
  SOCI,
  WMST,
  MEJO,
  INLS,
  BUSI,
  EDUC,
  NURS,
  PHCY,
  HBEH
}